# This is a basic workflow to help you get started with Actions

name: CI
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node@${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Npm install
        run: |
          npm install
          npm run build
          echo `pwd`
          echo `ls -al`

      - name: Setup environment
        run: |
          mkdir -p ~/.ssh/
          echo "${DEPLOY_POSTS_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "cjystyle@163.com"
          git config --global user.name "Avery"
      
      - name: Pull origin blog project
        run: |
          cd ~/work
          git clone git@github.com:yantul/yantul.github.io.git
          git checkout master
          # cp -r ~/work/blog/blog/dist/js/* ./yantul.github.io/script/
          # cp -r ~/work/blog/blog/dist/css/* ./yantul.github.io/style/
          # cp ~/work/blog/blog/dist/*.css ./yantul.github.io/
          # cp 
          cp ~/work/blog/blog/dist/index.html ./yantul.github.io/
          echo `pwd`
          

      - name: Deploy blog
        run: |
          echo `pwd`
          git add -A
          git commit -m "Update Blog Theme."
          
        
